twist_mux:
  ros__parameters:
    topics:
      navigation:
       topic: cmd_vel
       timeout: 0.5
       priority: 10
      manual:
       topic: cmd_vel_manual  # manual input node
       timeout: 0.5
       priority: 100
